name: employees_app
description: "Diffusely case-study."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & State management
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  json_annotation: ^4.9.0

  # Localization
  easy_localization: ^3.0.8

  # Services
  dio: ^5.9.0
  collection: ^1.19.1
  sembast: ^3.8.6
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Architecture & State management (generated)
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
